### ISSUE TITLE
[Burn-P3+ Prometheus FR]: All jobs on a core in 1 pandora workfile

### ISSUE THREAD

**Issue by BadgerOnABike** [BurnP3/BurnP3PlusPrometheus#10]
### Contact Details

@badgeronabike

### What is needed?

Currently the parameter file is 1 fire at a time. This results in pandora instantiating prometheus over and over which has a popup window (CMD) that steals focus. We don't need that and all the jobs can be done at once. This does complicate aggregation a little bit, but I think it's worthwhile.

So what needs to be done?

- [ ] All fire designated to a single core would be in a parameter file to burn all at once.

Aggregation issues:

- [ ] High likelihood that aggregation will require tweaking to read the fid and it id to move things through. This should be a minor tweak

### How will this improve the project or tool?

You can keep using your computer!

### Approvals Process

- [ ] Testing For Issue
- [ ] Merge

**Comment by BadgerOnABike** [comment]
I believe this was satisfied by @shreeramsenthi as we have the batch system. Can I close this?

**Comment by shreeramsenthi** [comment]
As mentioned above, this is (mostly) resolved with batching
