### ISSUE TITLE
Remove Fuels Ascii generation and point to fuels.tif

### ISSUE THREAD

**Issue by BadgerOnABike** [BurnP3/BurnP3PlusPrometheus#5]
Currently we are populating an ascii for the fuels, which isn't necessary at all. Adjustments are simple to sort out some small writing tasks and improve overall speed.

**Comment by shreeramsenthi** [comment]
FYI I did try doing this during development and ran into an issue. I forget my rationale, but I think I eventually decided it wasn't worth pursuing due to an issue with Pandora not ingesting TIF fuel maps correctly. I could have been wrong or that could have been fixed already.

**Comment by BadgerOnABike** [comment]
I believe this was due to an earlier version of Pandora, I pulled this out and it didn't seem to have any appreciable effect.

**Comment by BadgerOnABike** [comment]
Fixed with #9
